/*
 * Created on 1 Sep 2017 ( Time 15:57:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.zeta.mobile.direct.offers.entities;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Persistent class for entity stored in table "campaignoffers"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name = "campaign_offers", catalog = "directoffers")
// Define named queries here
@NamedQueries({ @NamedQuery(name = "CampaignOffer.countAll", query = "SELECT COUNT(x) FROM CampaignOffer x"),
		@NamedQuery(name = "CampaignOffer.findByOperatorAndCampaign", query = "SELECT x FROM CampaignOffer x where x.carrier= :carrier and x.campaign= :campaign") })
public class CampaignOffer implements Serializable {

	private static final long serialVersionUID = 1L;

	// ----------------------------------------------------------------------
	// ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
	// ----------------------------------------------------------------------
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", nullable = false)
	private Long id;

	// ----------------------------------------------------------------------
	// ENTITY DATA FIELDS
	// ----------------------------------------------------------------------
	@Column(name = "external_id", nullable = false)
	private String externalId;

	@Column(name = "name", nullable = false)
	private String name;

	@Column(name = "pre_jump_url")
	private String prejumpurl;

	@Column(name = "jump_url", nullable = false)
	private String jumpurl;

	@Column(name = "created_by", nullable = false)
	private String createdby;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", nullable = false)
	private Date creationdate;

	@Column(name = "edited_by")
	private String editedby;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "edition_date")
	private Date editiondate;

	@OneToMany(mappedBy = "campaignOffer", targetEntity = Subscription.class)
	@JsonBackReference
	private List<Subscription> listOfSubscriptions;

	@ManyToOne
	@JoinColumn(name = "price_point_plan_id", referencedColumnName = "id")
	@JsonManagedReference
	private PricePointPlan pricepointplan;

	@JoinColumn(name = "carrier_id", referencedColumnName = "id", insertable = false, updatable = false)
	@ManyToOne
	@JsonManagedReference
	private Carrier carrier;

	@ManyToOne
	@JoinColumn(name = "campaign_id", referencedColumnName = "id")
	@JsonManagedReference
	private Campaign campaign;

	// ----------------------------------------------------------------------
	// CONSTRUCTOR(S)
	// ----------------------------------------------------------------------
	public CampaignOffer() {
		super();
	}

	// ----------------------------------------------------------------------
	// GETTER & SETTER FOR THE KEY FIELD
	// ----------------------------------------------------------------------
	public void setId(Long id) {
		this.id = id;
	}

	public Long getId() {
		return this.id;
	}

	public void setExternalId(String externalId) {
		this.externalId = externalId;
	}

	public String getExternalId() {
		return this.externalId;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getName() {
		return this.name;
	}

	public void setPrejumpurl(String prejumpurl) {
		this.prejumpurl = prejumpurl;
	}

	public String getPrejumpurl() {
		return this.prejumpurl;
	}

	public void setJumpurl(String jumpurl) {
		this.jumpurl = jumpurl;
	}

	public String getJumpurl() {
		return this.jumpurl;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreationdate(Date creationdate) {
		this.creationdate = creationdate;
	}

	public Date getCreationdate() {
		return this.creationdate;
	}

	public void setEditedby(String editedby) {
		this.editedby = editedby;
	}

	public String getEditedby() {
		return this.editedby;
	}

	public void setEditiondate(Date editiondate) {
		this.editiondate = editiondate;
	}

	public Date getEditiondate() {
		return this.editiondate;
	}

	public void setPricepointplan(PricePointPlan pricepointplan) {
		this.pricepointplan = pricepointplan;
	}

	public PricePointPlan getPricepointplan() {
		return this.pricepointplan;
	}

	public void setCampaigns(Campaign campaigns) {
		this.campaign = campaigns;
	}

	public Campaign getCampaigns() {
		return this.campaign;
	}

	public List<Subscription> getListOfSubscriptions() {
		return listOfSubscriptions;
	}

	public void setListOfSubscriptions(List<Subscription> listOfSubscriptions) {
		this.listOfSubscriptions = listOfSubscriptions;
	}

	public Campaign getCampaign() {
		return campaign;
	}

	public void setCampaign(Campaign campaign) {
		this.campaign = campaign;
	}

	public Carrier getCarrier() {
		return carrier;
	}

	public void setCarrier(Carrier carrier) {
		this.carrier = carrier;
	}

}
