/*
 * Created on 1 Sep 2017 ( Time 15:57:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.zeta.mobile.direct.offers.entities;
import java.io.Serializable;

import javax.persistence.*;

/**
 * Composite primary key for entity "CarriersEntity" ( stored in table "carriers" )
 *
 * @author Telosys Tools Generator
 *
 */
 @Embeddable
public class CarriersEntityKey implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;
    
    @Column(name="connectionId", nullable=false)
    private Integer    connectionid ;
    
    @Column(name="countryCode", nullable=false)
    private Integer    countrycode  ;
    

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public CarriersEntityKey() {
        super();
    }

    public CarriersEntityKey( Integer id, Integer connectionid, Integer countrycode ) {
        super();
        this.id = id ;
        this.connectionid = connectionid ;
        this.countrycode = countrycode ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
    public void setId( Integer value ) {
        this.id = value;
    }
    public Integer getId() {
        return this.id;
    }

    public void setConnectionid( Integer value ) {
        this.connectionid = value;
    }
    public Integer getConnectionid() {
        return this.connectionid;
    }

    public void setCountrycode( Integer value ) {
        this.countrycode = value;
    }
    public Integer getCountrycode() {
        return this.countrycode;
    }


    //----------------------------------------------------------------------
    // equals METHOD
    //----------------------------------------------------------------------
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		CarriersEntityKey other = (CarriersEntityKey) obj; 
		//--- Attribute id
		if ( id == null ) { 
			if ( other.id != null ) 
				return false ; 
		} else if ( ! id.equals(other.id) ) 
			return false ; 
		//--- Attribute connectionid
		if ( connectionid == null ) { 
			if ( other.connectionid != null ) 
				return false ; 
		} else if ( ! connectionid.equals(other.connectionid) ) 
			return false ; 
		//--- Attribute countrycode
		if ( countrycode == null ) { 
			if ( other.countrycode != null ) 
				return false ; 
		} else if ( ! countrycode.equals(other.countrycode) ) 
			return false ; 
		return true; 
	} 


    //----------------------------------------------------------------------
    // hashCode METHOD
    //----------------------------------------------------------------------
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute id
		result = prime * result + ((id == null) ? 0 : id.hashCode() ) ; 
		//--- Attribute connectionid
		result = prime * result + ((connectionid == null) ? 0 : connectionid.hashCode() ) ; 
		//--- Attribute countrycode
		result = prime * result + ((countrycode == null) ? 0 : countrycode.hashCode() ) ; 
		
		return result; 
	} 


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
		StringBuffer sb = new StringBuffer(); 
		sb.append(id); 
		sb.append("|"); 
		sb.append(connectionid); 
		sb.append("|"); 
		sb.append(countrycode); 
        return sb.toString();
    }
}
