/*
 * Created on 1 Sep 2017 ( Time 15:57:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.zeta.mobile.direct.offers.entities;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Persistent class for entity stored in table "charginghistory"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name = "charging_history", catalog = "directoffers")
// Define named queries here
@NamedQueries({ @NamedQuery(name = "ChargingHistory.countAll", query = "SELECT COUNT(x) FROM ChargingHistory x") })
public class ChargingHistory implements Serializable {

	private static final long serialVersionUID = 1L;

	// ----------------------------------------------------------------------
	// ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
	// ----------------------------------------------------------------------
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", nullable = false)
	private Long id;

	// ----------------------------------------------------------------------
	// ENTITY DATA FIELDS
	// ----------------------------------------------------------------------
	@Column(name = "status", length = 45)
	private String status;

	@Column(name = "externalId")
	private Long externalid;

	@Column(name = "paymentType", nullable = false)
	private String paymenttype;

	// ----------------------------------------------------------------------
	// ENTITY LINKS ( RELATIONSHIP )
	// ----------------------------------------------------------------------

	// ----------------------------------------------------------------------
	// CONSTRUCTOR(S)
	// ----------------------------------------------------------------------
	public ChargingHistory() {
		super();
	}

	// ----------------------------------------------------------------------
	// GETTER & SETTER FOR THE KEY FIELD
	// ----------------------------------------------------------------------
	public void setId(Long id) {
		this.id = id;
	}

	public Long getId() {
		return this.id;
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR FIELDS
	// ----------------------------------------------------------------------
	// --- DATABASE MAPPING : status ( VARCHAR )
	public void setStatus(String status) {
		this.status = status;
	}

	public String getStatus() {
		return this.status;
	}

	// --- DATABASE MAPPING : externalId ( INT )
	public void setExternalid(Long externalid) {
		this.externalid = externalid;
	}

	public Long getExternalid() {
		return this.externalid;
	}

	// --- DATABASE MAPPING : paymentType ( TEXT )
	public void setPaymenttype(String paymenttype) {
		this.paymenttype = paymenttype;
	}

	public String getPaymenttype() {
		return this.paymenttype;
	}

	@Override
	public String toString() {
		return "ChargingHistory [id=" + id + ", status=" + status + ", externalid=" + externalid + ", paymenttype="
				+ paymenttype + "]";
	}

}
