/*
 * Created on 1 Sep 2017 ( Time 12:54:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.zeta.mobile.direct.offers.entities;
import java.io.Serializable;

import javax.persistence.*;

/**
 * Composite primary key for entity "ConnectionsEntity" ( stored in table "connections" )
 *
 * @author Telosys Tools Generator
 *
 */
 @Embeddable
public class ConnectionsEntityKey implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;
    
    @Column(name="currencyId", nullable=false)
    private Integer    currencyid   ;
    

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public ConnectionsEntityKey() {
        super();
    }

    public ConnectionsEntityKey( Integer id, Integer currencyid ) {
        super();
        this.id = id ;
        this.currencyid = currencyid ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
    public void setId( Integer value ) {
        this.id = value;
    }
    public Integer getId() {
        return this.id;
    }

    public void setCurrencyid( Integer value ) {
        this.currencyid = value;
    }
    public Integer getCurrencyid() {
        return this.currencyid;
    }


    //----------------------------------------------------------------------
    // equals METHOD
    //----------------------------------------------------------------------
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		ConnectionsEntityKey other = (ConnectionsEntityKey) obj; 
		//--- Attribute id
		if ( id == null ) { 
			if ( other.id != null ) 
				return false ; 
		} else if ( ! id.equals(other.id) ) 
			return false ; 
		//--- Attribute currencyid
		if ( currencyid == null ) { 
			if ( other.currencyid != null ) 
				return false ; 
		} else if ( ! currencyid.equals(other.currencyid) ) 
			return false ; 
		return true; 
	} 


    //----------------------------------------------------------------------
    // hashCode METHOD
    //----------------------------------------------------------------------
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute id
		result = prime * result + ((id == null) ? 0 : id.hashCode() ) ; 
		//--- Attribute currencyid
		result = prime * result + ((currencyid == null) ? 0 : currencyid.hashCode() ) ; 
		
		return result; 
	} 


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
		StringBuffer sb = new StringBuffer(); 
		sb.append(id); 
		sb.append("|"); 
		sb.append(currencyid); 
        return sb.toString();
    }
}
