/*
 * Created on 1 Sep 2017 ( Time 15:57:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.zeta.mobile.direct.offers.entities;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * Persistent class for entity stored in table "currencies"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name = "currencies", catalog = "directoffers")
// Define named queries here
@NamedQueries({ @NamedQuery(name = "Currency.countAll", query = "SELECT COUNT(x) FROM Currency x") })
public class Currency implements Serializable {

	private static final long serialVersionUID = 1L;

	// ----------------------------------------------------------------------
	// ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
	// ----------------------------------------------------------------------
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", nullable = false)
	private Long id;

	// ----------------------------------------------------------------------
	// ENTITY DATA FIELDS
	// ----------------------------------------------------------------------
	@Column(name = "currency", nullable = false)
	private String currency;

	@Column(name = "iso_code", nullable = false)
	private String isocode;

	@Column(name = "iso_symbol", nullable = false)
	private String isosymbol;

	@Column(name = "thousands_separator", nullable = false)
	private String thousandsSeparator;

	@Column(name = "decimal_separator", nullable = false)
	private String decimalSeparator;

	@Column(name = "symbol_position")
	private String symbolPosition;

	@OneToMany(mappedBy = "currencies", targetEntity = PricePointPlan.class)
	@JsonBackReference
	private List<PricePointPlan> listOfPricepointplan;

	public Currency() {
		super();
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getId() {
		return this.id;
	}

	public void setIsocode(String isocode) {
		this.isocode = isocode;
	}

	public String getIsocode() {
		return this.isocode;
	}

	public void setIsosymbol(String isosymbol) {
		this.isosymbol = isosymbol;
	}

	public String getIsosymbol() {
		return this.isosymbol;
	}

	public String getCurrency() {
		return currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public String getThousandsSeparator() {
		return thousandsSeparator;
	}

	public void setThousandsSeparator(String thousandsSeparator) {
		this.thousandsSeparator = thousandsSeparator;
	}

	public String getDecimalSeparator() {
		return decimalSeparator;
	}

	public void setDecimalSeparator(String decimalSeparator) {
		this.decimalSeparator = decimalSeparator;
	}

	public List<PricePointPlan> getListOfPricepointplan() {
		return listOfPricepointplan;
	}

	public void setListOfPricepointplan(List<PricePointPlan> listOfPricepointplan) {
		this.listOfPricepointplan = listOfPricepointplan;
	}

}
