/*
 * Created on 1 Sep 2017 ( Time 15:57:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.zeta.mobile.direct.offers.entities;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Persistent class for entity stored in table "impressions"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name = "impressions", catalog = "directoffers")
// Define named queries here
@NamedQueries({ @NamedQuery(name = "Impression.countAll", query = "SELECT COUNT(x) FROM Impression x"),
		@NamedQuery(name = "Impression.findById", query = "SELECT x FROM Impression x where x.id = :id") })
public class Impression implements Serializable {

	private static final long serialVersionUID = 1L;

	// ----------------------------------------------------------------------
	// ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
	// ----------------------------------------------------------------------
	@Id
	@Column(name = "id", nullable = false)
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long id;

	// ----------------------------------------------------------------------
	// ENTITY DATA FIELDS
	// ----------------------------------------------------------------------
	@Column(name = "time_zone")
	private String timezone;

	@Column(name = "browser_language")
	private String browserlanguage;

	@Column(name = "platform")
	private String platform;

	@Column(name = "broswer")
	private String broswer;

	@Column(name = "source_ip")
	private String sourceip;

	@Column(name = "screen_size")
	private String screensize;

	@Column(name = "device")
	private String device;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date")
	private Date creationdate;

	@Column(name = "created_by")
	private String createdby;

	@Column(name = "impression_url")
	private String impressionUrl;

	@JoinColumn(name = "campaignid", referencedColumnName = "id", nullable = false, insertable = true, updatable = false)
	@ManyToOne
	@JsonManagedReference
	private Campaign campaign;

	public Impression() {
		super();
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getId() {
		return this.id;
	}

	public void setScreensize(String screensize) {
		this.screensize = screensize;
	}

	public String getScreensize() {
		return this.screensize;
	}

	// --- DATABASE MAPPING : timeZone ( INT )
	public void setTimezone(String timezone) {
		this.timezone = timezone;
	}

	public String getTimezone() {
		return this.timezone;
	}

	// --- DATABASE MAPPING : broswerLanguage ( TEXT )
	public void setBrowserlanguage(String broswerlanguage) {
		this.browserlanguage = broswerlanguage;
	}

	public String getBrowserlanguage() {
		return this.browserlanguage;
	}

	// --- DATABASE MAPPING : platform ( TEXT )
	public void setPlatform(String platform) {
		this.platform = platform;
	}

	public String getPlatform() {
		return this.platform;
	}

	// --- DATABASE MAPPING : broswer ( TEXT )
	public void setBroswer(String broswer) {
		this.broswer = broswer;
	}

	public String getBroswer() {
		return this.broswer;
	}

	// --- DATABASE MAPPING : sourceIp ( TEXT )
	public void setSourceip(String sourceip) {
		this.sourceip = sourceip;
	}

	public String getSourceip() {
		return this.sourceip;
	}

	// --- DATABASE MAPPING : creationDate ( TIMESTAMP )
	public void setCreationdate(Date creationdate) {
		this.creationdate = creationdate;
	}

	public Date getCreationdate() {
		return this.creationdate;
	}

	// --- DATABASE MAPPING : createdBy ( TIMESTAMP )
	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	public String getCreatedby() {
		return this.createdby;
	}

	public String getDevice() {
		return device;
	}

	public void setDevice(String device) {
		this.device = device;
	}

	public String getImpressionUrl() {
		return impressionUrl;
	}

	public void setImpressionUrl(String impressionUrl) {
		this.impressionUrl = impressionUrl;
	}

	public Campaign getCampaign() {
		return campaign;
	}

	public void setCampaign(Campaign campaign) {
		this.campaign = campaign;
	}

}
