/*
 * Created on 1 Sep 2017 ( Time 15:57:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.zeta.mobile.direct.offers.entities;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Persistent class for entity stored in table "pricepointplan"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name = "price_point_plan", catalog = "directoffers")
// Define named queries here
@NamedQueries({ @NamedQuery(name = "PricePointPlan.countAll", query = "SELECT COUNT(x) FROM PricePointPlan x") })
public class PricePointPlan implements Serializable {

	private static final long serialVersionUID = 1L;

	// ----------------------------------------------------------------------
	// ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
	// ----------------------------------------------------------------------
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", nullable = false)
	private Long id;

	@Column(name = "external_id", nullable = false)
	private String externalId;

	// ----------------------------------------------------------------------
	// ENTITY DATA FIELDS
	// ----------------------------------------------------------------------

	@Column(name = "value", nullable = false)
	private Double value;

	@Column(name = "frequency", nullable = false)
	private Integer frequency;

	@Column(name = "retry_on_fail")
	private Boolean retryonfail;

	@Column(name = "retry_count")
	private int retryCount;

	@Column(name = "minutes_before_retry")
	private int minutesBeforeRetry;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date")
	private Date creationdate;

	@Column(name = "created_by")
	private String createdby;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "edition_date")
	private Date editiondate;

	@Column(name = "edited_by")
	private String editedby;

	@Column(name = "name")
	private String name;

	@Column(name = "pay_type")
	private String payType;

	@Column(name = "is_auto_renew")
	private Boolean isAutoRenew;

	// ----------------------------------------------------------------------
	// ENTITY LINKS ( RELATIONSHIP )
	// ----------------------------------------------------------------------
	@OneToMany(mappedBy = "pricepointplan", targetEntity = CampaignOffer.class)
	@JsonBackReference
	private List<CampaignOffer> listOfCampaignOffers;

	@JoinColumn(name = "currency_id", referencedColumnName = "id", insertable = false, updatable = false)
	@ManyToOne
	@JsonManagedReference
	private Currency currencies;

	// ----------------------------------------------------------------------
	// CONSTRUCTOR(S)
	// ----------------------------------------------------------------------
	public PricePointPlan() {
		super();
	}

	// ----------------------------------------------------------------------
	// GETTER & SETTER FOR THE KEY FIELD
	// ----------------------------------------------------------------------
	public void setId(Long id) {
		this.id = id;
	}

	public Long getId() {
		return this.id;
	}

	// --- DATABASE MAPPING : frequency ( INT )
	public void setFrequency(Integer frequency) {
		this.frequency = frequency;
	}

	public Integer getFrequency() {
		return this.frequency;
	}

	// --- DATABASE MAPPING : creationDate ( TIMESTAMP )
	public void setCreationdate(Date creationdate) {
		this.creationdate = creationdate;
	}

	public Date getCreationdate() {
		return this.creationdate;
	}

	// --- DATABASE MAPPING : createdBy ( TEXT )
	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	public String getCreatedby() {
		return this.createdby;
	}

	// --- DATABASE MAPPING : editionDate ( TIMESTAMP )
	public void setEditiondate(Date editiondate) {
		this.editiondate = editiondate;
	}

	public Date getEditiondate() {
		return this.editiondate;
	}

	public Double getValue() {
		return value;
	}

	public void setValue(Double value) {
		this.value = value;
	}

	public Boolean getRetryonfail() {
		return retryonfail;
	}

	public void setRetryonfail(Boolean retryonfail) {
		this.retryonfail = retryonfail;
	}

	public int getRetryCount() {
		return retryCount;
	}

	public void setRetryCount(int retryCount) {
		this.retryCount = retryCount;
	}

	public int getMinutesBeforeRetry() {
		return minutesBeforeRetry;
	}

	public void setMinutesBeforeRetry(int minutesBeforeRetry) {
		this.minutesBeforeRetry = minutesBeforeRetry;
	}

	// --- DATABASE MAPPING : editedBy ( TEXT )
	public void setEditedby(String editedby) {
		this.editedby = editedby;
	}

	public String getEditedby() {
		return this.editedby;
	}

	public List<CampaignOffer> getListOfCampaignOffers() {
		return listOfCampaignOffers;
	}

	public void setListOfCampaignOffers(List<CampaignOffer> listOfCampaignOffers) {
		this.listOfCampaignOffers = listOfCampaignOffers;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Currency getCurrencies() {
		return currencies;
	}

	public void setCurrencies(Currency currencies) {
		this.currencies = currencies;
	}

	public String getExternalId() {
		return externalId;
	}

	public void setExternalId(String externalId) {
		this.externalId = externalId;
	}

	public String getPayType() {
		return payType;
	}

	public void setPayType(String payType) {
		this.payType = payType;
	}

	public Boolean getIsAutoRenew() {
		return isAutoRenew;
	}

	public void setIsAutoRenew(Boolean isAutoRenew) {
		this.isAutoRenew = isAutoRenew;
	}

}
