/*
 * Created on 1 Sep 2017 ( Time 15:57:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.zeta.mobile.direct.offers.entities;

import java.io.Serializable;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.zeta.mobile.direct.offers.entities.helpers.PricePointType;

@Entity
@Table(name = "price_plan", catalog = "directoffers")
@NamedQueries({ @NamedQuery(name = "PricePlan.countAll", query = "SELECT COUNT(x) FROM PricePlan x") })
public class PricePlan implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", nullable = false)
	private Long id;

	@Column(name = "external_id", nullable = false)
	private String externalId;
	
	@Column(name = "name")
	private String name;

	@OneToMany(mappedBy = "pricePlan", targetEntity = CampaignOffer.class)
	@JsonBackReference
	private List<CampaignOffer> listOfCampaignOffers;

	@JoinColumn(name = "currency_id", referencedColumnName = "id", insertable = false, updatable = false)
	@ManyToOne
	@JsonManagedReference
	private Currency currencies;
	
	@OneToMany(mappedBy = "pricePlan", targetEntity = PricePoint.class)
	@JsonBackReference
	private List<PricePoint> listOfPricePoint;
	
	
	public PricePlan() {
		super();
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getId() {
		return this.id;
	}

	public List<CampaignOffer> getListOfCampaignOffers() {
		return listOfCampaignOffers;
	}

	public void setListOfCampaignOffers(List<CampaignOffer> listOfCampaignOffers) {
		this.listOfCampaignOffers = listOfCampaignOffers;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Currency getCurrencies() {
		return currencies;
	}

	public void setCurrencies(Currency currencies) {
		this.currencies = currencies;
	}

	public String getExternalId() {
		return externalId;
	}

	public void setExternalId(String externalId) {
		this.externalId = externalId;
	}

	public List<PricePoint> getListOfPricePoint() {
		return listOfPricePoint;
	}

	public PricePoint getPricePointByType(PricePointType type) {
		return getListOfPricePoint().stream().filter(pp -> pp.getType().equals(type))
	            .findFirst()
	            .get();
	}

	public void setListOfPricePoint(List<PricePoint> listOfPricePoint) {
		this.listOfPricePoint = listOfPricePoint;
	}
	
}
