-- MySQL Script generated by MySQL Workbench
-- Fri Sep  1 12:51:51 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema directoffers
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema directoffers
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `directoffers` DEFAULT CHARACTER SET utf8 ;
USE `directoffers` ;

-- -----------------------------------------------------
-- Table `directoffers`.`Currencies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `directoffers`.`Currencies` ;

CREATE TABLE IF NOT EXISTS `directoffers`.`Currencies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `isoCode` TEXT NOT NULL,
  `isoSymbol` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `directoffers`.`Connections`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `directoffers`.`Connections` ;

CREATE TABLE IF NOT EXISTS `directoffers`.`Connections` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT NOT NULL,
  `securityKey` TEXT NULL,
  `url` TEXT NULL,
  `supportPhoneNumber` TEXT NULL,
  `supportEmail` TEXT NULL,
  `supportSkype` TEXT NULL,
  `integrationType` TEXT NOT NULL COMMENT '(\"Broker\" , \"Carrier\")',
  `currencyId` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `currencyFK_idx` (`currencyId` ASC),
  CONSTRAINT `currency2FK`
    FOREIGN KEY (`currencyId`)
    REFERENCES `directoffers`.`Currencies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `directoffers`.`Countries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `directoffers`.`Countries` ;

CREATE TABLE IF NOT EXISTS `directoffers`.`Countries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT NOT NULL,
  `isoName` TEXT NOT NULL,
  `region` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `directoffers`.`Carriers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `directoffers`.`Carriers` ;

CREATE TABLE IF NOT EXISTS `directoffers`.`Carriers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `connectionId` INT NOT NULL,
  `countryCode` INT NOT NULL COMMENT 'mobile contry code',
  `networkCode` INT NOT NULL COMMENT 'mobile network code',
  `name` TEXT NULL,
  PRIMARY KEY (`id`, `connectionId`, `countryCode`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `mcc_UNIQUE` (`countryCode` ASC),
  INDEX `connectionFK_idx` (`connectionId` ASC),
  CONSTRAINT `countryFK`
    FOREIGN KEY (`countryCode`)
    REFERENCES `directoffers`.`Countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `connectionFK`
    FOREIGN KEY (`connectionId`)
    REFERENCES `directoffers`.`Connections` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `directoffers`.`Campaigns`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `directoffers`.`Campaigns` ;

CREATE TABLE IF NOT EXISTS `directoffers`.`Campaigns` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `connectionId` INT NOT NULL,
  `name` INT NOT NULL,
  `typeOfTraffic` TEXT NOT NULL,
  `extenalId` INT NOT NULL,
  `countryId` VARCHAR(45) NOT NULL,
  `creationDate` TIMESTAMP NOT NULL,
  `createdBy` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `connectionFK_idx` (`connectionId` ASC),
  CONSTRAINT `connection2FK`
    FOREIGN KEY (`connectionId`)
    REFERENCES `directoffers`.`Connections` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `directoffers`.`PricePointPlan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `directoffers`.`PricePointPlan` ;

CREATE TABLE IF NOT EXISTS `directoffers`.`PricePointPlan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `carrierId` INT NOT NULL,
  `tax` DOUBLE NOT NULL COMMENT '0 means free',
  `frequency` INT NOT NULL COMMENT '0 means one time payment',
  `start_period` TIMESTAMP NULL,
  `end_period` TIMESTAMP NULL,
  `retryOnFail` TINYINT NULL,
  `topUp` TINYINT NOT NULL,
  `creationDate` TIMESTAMP NULL,
  `createdBy` TEXT NULL,
  `editionDate` TIMESTAMP NULL,
  `editedBy` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `directoffers`.`CampaignOffers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `directoffers`.`CampaignOffers` ;

CREATE TABLE IF NOT EXISTS `directoffers`.`CampaignOffers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `externalId` INT NOT NULL,
  `campaignId` INT NOT NULL,
  `name` TEXT NOT NULL,
  `pricePointPlanId` INT NOT NULL,
  `preJumpUrl` TEXT NULL,
  `jumpUrl` TEXT NOT NULL,
  `createdBy` TEXT NOT NULL,
  `creationDate` TIMESTAMP NOT NULL,
  `editedBy` TEXT NULL,
  `editionDate` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `CampaignsFK_idx` (`campaignId` ASC),
  INDEX `PricePointFK_idx` (`pricePointPlanId` ASC),
  CONSTRAINT `CampaignsFK`
    FOREIGN KEY (`campaignId`)
    REFERENCES `directoffers`.`Campaigns` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PricePointFK`
    FOREIGN KEY (`pricePointPlanId`)
    REFERENCES `directoffers`.`PricePointPlan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `directoffers`.`Impressions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `directoffers`.`Impressions` ;

CREATE TABLE IF NOT EXISTS `directoffers`.`Impressions` (
  `id` INT NOT NULL,
  `msisdn` TEXT NULL,
  `screenSize` TEXT NULL,
  `timeZone` INT NULL,
  `broswerLanguage` TEXT NULL,
  `platform` TEXT NULL,
  `broswer` TEXT NULL,
  `sourceIp` TEXT NULL,
  `offerId` INT NULL,
  `creationDate` TIMESTAMP NULL,
  `createdBy` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `OfferFK_idx` (`offerId` ASC),
  CONSTRAINT `OfferFK`
    FOREIGN KEY (`offerId`)
    REFERENCES `directoffers`.`CampaignOffers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `directoffers`.`Subscriptions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `directoffers`.`Subscriptions` ;

CREATE TABLE IF NOT EXISTS `directoffers`.`Subscriptions` (
  `id` INT NOT NULL,
  `status` TEXT NOT NULL,
  `impressionId` INT NULL,
  `externalId` VARCHAR(45) NULL COMMENT 'contractID from tpay',
  `paymentType` VARCHAR(45) NULL,
  `subscriptionPayStatus` TEXT NOT NULL,
  `accountId` INT NOT NULL,
  `nextRenewDate` TIMESTAMP NOT NULL,
  `creationDate` TIMESTAMP NOT NULL,
  `createdBy` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `impressionFK_idx` (`impressionId` ASC),
  CONSTRAINT `impressionFK`
    FOREIGN KEY (`impressionId`)
    REFERENCES `directoffers`.`Impressions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `directoffers`.`ChargingHistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `directoffers`.`ChargingHistory` ;

CREATE TABLE IF NOT EXISTS `directoffers`.`ChargingHistory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL COMMENT 'success, \nwaiting, failed',
  `impressionId` INT NOT NULL,
  `externalId` INT NULL,
  `paymentType` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
