<?php
  
    Class Numerology
    {
		
        private $numerology_data=array();
		
		public function __construct() 
		{
			//define associative array here
			$this->numerology_data[0] = array(
			"number"   =>1, 
			"significance" =>"إذا كان لدى الشخص مسار الحياة الرقم 1 ، فهو قائد بالفطرة . يصر على حقه في رأيه ، و ويطالب بحرية الفكر والعمل . لديه الدافع والتصميم ولا يدع أي شيء أو أي شخص يقف في طريقه والتزامه لتحقيق هدفه .يتحمل المسؤولية ويكون حامي وواقي وراعي ومزود لأحبائه . يطالب بالاحترام والاهتمام ، ويغضب ويستبد عندما لا تسير الامور وفق تطلعاته وهو بحاجة للشعور بقيادته  المشاريع الهامة ويزاول ادوار هامة ويسعى دائماً الى الأمامية و الأضواء. بما ان هذا المسار هو الأول فصاحبه شديد المنافسة .لطالما يسعى للفوز ، يكره الخسارة ، طموح و خياله واسع . .لكنه في نفس الوقت متفهم ، و حكيم أيضا ، ومعروف على أنه طيب الخلق و مبدع  و في اتباع كبير لحدسه . وواثق من نفسه زيادة عن اللزوم. ما يميز  الشخص في المسار رقم 1 هو كونه حنون للغاية و عطوف ، لطالما يتعاطف مع الآخرين عن قريب أو عن بعيد ، يحب الجدية في الحب ، مرحب بالعلاقات الجدية دون تردد  ،  يكره بشدة الوحدة والانفصال ، كما أنه شاعري لحد كبير. و رومانسي أيضا ، يحب مشاطرة الوسائط  الشاعرية مع الحبيب .  التي تحوي جوا مميزا. و سماع الموسيقى العاطفية،  و الروحانية. و السباحة مع الشريك .   صاحب المسار رقم 1 مع أنه لا يحب الوحدة إلا أنه يختار أصدقائه بعناية. أي أنه يفضل الوحدة على ان يصاحب الناس الخطأ . يكون كئيبا عندما يترك لوحده، حالم بالمستقبل البعيد وحسّاس للغاية، يثق بالجميع مما يجعله دائما الضحية، يعشق المكوث في الوسائط المرئية. كما أنه كاتم جيد للأسرار. وصديق شهم.  وايضا يحب أجواء المرح و الرفاهية و الضحك . صاحب المسار رقم 1 طموح جدا،  كما قلنا يفعل أي شيء من أجل الفوز والتقدم على الخصم مهما كان الثمن، كما أنه يحزن كثيرا عندما يفشل أو عندما يخسر مبلغا من الم.  لكنه على العموم لا يفقد الأمل من الخسارة الأولى . لكنه جادا في عمله كما في صداقاته. . كما انه ينجز أعماله باحترافية وبإتقان شديدين . لا يغامر كثيرا وذلك لتفادي الخسارة سواء كانت كبيرة أو صغيرة، لكنه إذا وجد جوا مناسبا فإنه يغتنم الفرص. ولا يدعها تمر دون استغلال، ولكنه يتفادى المجازفة والاقتراب الى دوائر الخطر .  صاحب المسار رقم 1 يقدس جسمه كثيرا فهو يعتقد ان الصحة هي اهم ما يمتلكه الانسان . لذلك نجده يخاف على نفسه كثيرا من الأذى الخارجي . أي أنه يتجنب الأفعال التي قد تؤدي الى المساس بصحته أو بجسده  ، ما يثير استياء ما من حوله . كما أنه يعشق النوم والراحة., ",
			"url"=>"numberlogia.ar.zmobs.com",
			"en"=>"If a person has the path of life No. 1, he is a natural leader, insists on his right to his opinion, demands freedom of thought and action, has the motivation and determination and leaves nothing, or anyone who stands in his way and commitment to achieve his goal. He demands respect and attention, and gets angry when he does not go according to his expectations, he needs to feel his leadership of important projects and he plays important roles and always seeks the front and the lights, since this track is the first and his partner is very competitive. But at the same time understanding, and wise Also, he is known for being good-natured, creative and in following a great deal of his intuition, and he is more confident than himself What distinguishes the person in track number 1 is that he is very compassionate and compassionate, always sympathetic to others close or far away, loves seriousness in love , Loves serious relationships without hesitation, strongly dislikes unity and separation, is also a great poet, and also romantic, loves to share the poetic media with the beloved, which contains a distinctive atmosphere, listening to emotional music, spirituality and swimming with partner. His track number 1 though he does not like loneliness but he chooses his friends carefully. In other words, he prefers unity with the people accompanying the mistake. It is bleak when left alone, dreaming of a distant and very sensitive future, trusting everyone who always makes him the victim, and loves to stay in the visual media. It is also a good silencer for secrets. And a gentleman friend. And also loves the atmosphere of fun and luxury and laughter. The owner of track # 1 is very ambitious, as we have said, he does anything to win and advance at the opponent at any cost, and he is very sad when he fails or when he loses a sum of money. But on the whole does not lose hope of the first loss. But he is serious in his work as in his friendships. . He also performs his work professionally and with great proficiency. He does not take much risk to avoid loss, whether big or small, but if he finds the right atmosphere he takes advantage of opportunities. Does not allow it to pass without exploitation, but avoids risk and approach the circles of danger. The owner of Track No. 1 sanctifies his body a lot, he believes that health is the most important possession of man. . So we find him afraid of himself much external harm. . . . That is, it avoids acts that may affect his health or body, which raises resentment around him. He also loves sleep and rest. . .",
			);
			
			$this->numerology_data[1] = array(
			"number"   =>2, 
			"significance" =>"إذا كان لدى الشخص مسار الحياة الرقم 2 ، فهو بشكل طبيعي صانع سلام. حساس للغاية، مدرك وخجول بعض الشيء. هذه الصفات هي نقاط القوة والضعف لديك، لانك بينما تمتلك حساسية هائلة لمشاعرك وللاخرين، نفس الحساسية هذه يمكن أن يسبب تكبح وتقمع مواهبك الدفينة فيك . الحساسية والبصيرة هي بعض من بين العديد من الصفات الخاصة بك. 
			بما أن هذا المسار هو الثاني فصاحبه أمين جدا و صدوق، فضولي جدا، دائم التطلع و الاستكشاف، إنسان راقي جدا. أخلاقه عالية و طيب جدا ، لكنه متردد جدا و غريب الأطوار و أيضا قصير الباع ، متفتح جدا كما انه كريم كثيرا . يحب مشاركة الآخرين و يسعد بذلك كثيرا.
			ما يميز الشخص في المسار رقم 2 أنه متقلب المزاج، أي أن علاقاته غير ثابتة و مستقرة أي أن أفكاره مشوشة و من المستبعد أن يجد الشريك المناسب بسهولة.  لذلك تجده دائم البحث عن الشخص المناسب الذي قد يقتنع به أخيرا، و الذي قد يتحمل تقلب مزاجه و تشتت أفكاره.
			صاحب المسار رقم 2 اجتماعي جدا، تجده محبوب من طرف الكثيرين، عنده أصدقاء كثر. . . وفي لهم كثيرا ، على أتم استعداد أن يحارب من أجلهم ، أو أن يدافع عن قضية أحد منهم ، كما أنه يحب الاستماع إلى الآخرين وإجراء المحادثات العقلانية ، وأيضا يسعده كثيرا مساعدة الآخرين .
			صاحب المسار رقم2 عامل هادئ ، لا يميل كثيرا إلى الأمور المادية ، بل يفضل كل ما هو معنوي وجميل ، قدراته المهنية محدودة ، لأنه يحافظ على المبادئ والأساسيات البسيطة في الحياة . و يفضل البساطة و يكتفي بها. لا يفكر بمستقبله المهني بشكل جدي . لأنه يرى أن الوظيفة مجرد وسيلة لكسب المال لا غير.
			هو  محافظ على أخذ أدويته باستمرار ، وذلك لأنه يريد الشفاء بسرعة ، يكره الاصابة بأي مكروه ، يحاول جاهدا تفادي الإصابة بالعدوى . . . لذلك فانه يبتعد عن المرضى دائما دون مراعاة شعورهم ، يخاف الذهاب إلى المستشفيات .",
			"url"=>"numberlogia.ar.zmobs.com",
			"en"=>"If a person has the path of life number 2, he is naturally a peacemaker. Very sensitive, aware and a bit shy. These qualities are your strengths and weaknesses, because while you have a tremendous sensitivity to your feelings and others, this same sensitivity can inhibit and suppress your hidden talents. Sensitivity and insight are some of your many qualities.

			Since this track is the second, his companion is very honest and honest, very inquisitive, always looking and exploring, a very sophisticated man. His morals are high and very pleasant, but he is very hesitant, eccentric and also short-selling, very open-minded and he is also very generous. He likes to share with others and is so happy.
			What distinguishes a person in Track 2 is that he is moody, that is, his relationships are unstable and stable, that is, his thoughts are confused and it is unlikely that he will find the right partner easily. So you find him always searching for the right person who may be convinced of the end, which may bear the fluctuation of his mood and dispersion of his ideas.
			 Track # 2 is very social, you find him loved by many, he has many friends. . . He has a lot to fight for, to defend the cause of one of them, he likes to listen to others and make rational conversations, and he is also very happy to help others.
			His track No. 2 is a quiet worker, not much inclined to material things, but prefers all that is moral and beautiful, his professional abilities are limited, because he maintains the basic principles and basics in life. And prefer simplicity and content. Does not think about his professional career seriously. Because he felt that the job was just a way to make money only.
			He is constantly taking his medicine, because he wants to recover quickly, he hates injury, he tries hard to avoid infection. . . So he always moves away from the patients without taking into account their feelings, afraid to go to hospitals. . .",
			);
			
			
			$this->numerology_data[2] = array(
			"number"   =>3, 
			"significance" =>"ذا كان لدى الشخص مسار الحياة الرقم 3 ، فهو لديه موهبة كبيرة في الإبداع والتعبير عن الذات. يولد العديد من الكتاب والشعراء والممثلين والموسيقيين في إطار مسار الحياة الرقم 3. بارع، يمتلك هدية الثرثرة وتذوق الأضواء. موهبته الفنون التعبيرية ومع ذلك فان قدراته الفنية لا تنضج إلا من خلال الانضباط والالتزام بتطوير موهبته الحقيقية. بما إن هذا المسار هو الثالث فصاحبه أمين كتوم جدا وخجول، متسرع جدا، دائم الحيرة وخائف من المجهول، لكنه إنسان فريد من نوعه كثيرا. اخلاقه عظيمة وجميلة ، لكن ذاكرته قوية لا يحب المسامحة , لا ينسى , وسريع الانتقام وايضا حقود جدا  ، مع هذا فان له شأن كبير وشهرة واسعة النطاق كما انه محب كثيرا للافتخار والتباهي أمام الأخرين . ما يميز الشخص في المسار رقم 3 أنه وفي لشريكه ، لا يستسلم للإغراءات بسهولة ، أي أن علاقاته  ثابتة ومستقرة ، أي أن أفكاره لا تسودها الخيانة لكن من المستبعد أن يجد الشريك المناسب بسهولة . لذلك تجده دائم البحث عن الشخص المناسب الذي قديضع فيه ثقته الكاملة ويسلمه قلبه ويقتنع به أخيرا ، والذي قد يبادله الوفاء ويبادله نفس المشاعر الفياضة .  صاحب المسار رقم  3اجتماعي لكن ليس كثيرا ، تجده محبوب من طرف البعض  ، عنده بعضالأصدقاء الأوفياء الذي لا يريد أن يتركهم مهما كلف الأمر . كما أنه محط الهام عند البعض الذين يحترمونه كثيرا ، وهو على أتم استعداد أن يحارب من أجل علاقاته ، أو أن يدافع عن أحد منهم ، كما أنه يحب الاتكال على الاخرين واجراء المحادثات القصيرة ، وأيضا يسعده كثيرا التحدث عن مشاكله وهمومه امام المصادر المثقفة والموثوقة  . صاحب المسار رقم 3 محافظ على أداء الأنشطة البدنية باستمرار ، و ذلك لأنه يريد الحصول على جسد رشيق وأنيق بسرعة ، يكره الاصابة بأي مكروه ، يحاول جاهدا تفادي السمنة وزيادة الوزن . لذلك فانه يبتعد عن السكريات والدهون وكل ما هو مسبب للبدانة ، يخاف الذهاب الى الطبيب وأخذ حقن .",
			"url"=>"numberlogia.ar.zmobs.com",
			"en"=>"If a person has the No. 3 life path, he has a great talent for creativity and self-expression. Many writers, poets, actors and musicians are born within the framework of the No. 3 life path. He has a gift of chatter and tasting lights. His artistic talent is expressive yet his artistic abilities mature only through discipline and commitment to developing his true talent. Since this is the third track, Amin Qatoum is very shy, very hasty, always puzzled and afraid of the unknown, but he is a very unique person. His ethics are great and beautiful, but his memory is strong. He does not like forgiving, unforgettable, quick revenge and also very foolish, with this great fame and great fame as he is much fond of boasting and showing off in front of others. What distinguishes a person in Track 3 is that in his partner, he does not succumb to temptations easily, that is, his relationships are stable and stable, that is, his ideas are not dominated by treason, but it is unlikely to find the right partner easily. Therefore, you find him constantly searching for the right person in whom he placed his full confidence and delivered his heart and finally convinced him, which may reciprocate the fulfillment and exchange the same feelings of passion. His track number 3 social but not too much, you find loved by some, has a loyal Bedalosedka who does not want to leave them at any cost. He is also very interested in some people who respect him very much. He is willing to fight for his relations or to defend one of them. He also likes to rely on others and hold short talks. He is also very happy to talk about his problems and concerns to educated and reliable sources. The owner of Track No. 3 is constantly carrying out physical activities, because he wants to have a lean and stylish body quickly, hates injury with any dislike, tries hard to avoid obesity and weight gain. So he avoids sugars, fats and everything that causes obesity, afraid to go to the doctor and take injections.",
			);
				
			$this->numerology_data[3] = array(
			"number"   =>4, 
			"significance" =>"إذا كان لدى الشخص مسار الحياة الرقم 4 ، فهو عملي ومتواضع للفاية ، أفكاره قوية  وخاصة بالنسبة للعدالة وحول الصواب والخطأ. منظم ومنهجي ويسيطر علي الامور في حالة الفوضى، حاسم غير متردد، يتبع نهجا منطقي وخطوة بخطوة في حل المشكلات. عندما يحدد هدفه لا يتزحزح عنه ويسعى لنتفيذه مهما حصل.  بما أن هذا المسار هو الرابع فصاحبه شخصية عفوية، غير مترددة ولكنها كئيبة قليلا، دائمة القلق والخوف وخاصة أمام الجنس الأخر، لكنه إنسان غريب جدا. اخلاقه جيدة ، لكن كبرياءه عالية لا تهوى الذل ، لا يحب الانحطاط مطلقا , لا يكترث بالتعقيدات , وسريع الاستجابة مع الطرف الأخر . وايضا أماله عالية جدا جدا ، مع هذا فان له بعض المشاكل التي لا يريد مواجهتها امام العائلة , كما انه محب كثيرا لإخفاء المخاوف والتظاهر بالشجاعة أمام الأخرين خاصة . ما يميز الشخص في المسار رقم 4 أنه سعيد في علاقاته ، تسعده أبسط الأحاسيس وبسهولة ، أي أن نجاح علاقاته يكون بسبب عفويته وبساطته، وأفكاره بريئة، لكن من النادر أن يخلص لشريك حياته, وذلك لانقلاب مزاجاته. . . لذلك تجدهلا يوفي في علاقاته كثيرا, خاصة اتجاه ذلك الذي يلح كثيرا ، أو يطلب كثيرا من الأشياء . صاحب المسار رقم 4 ودود وطيب كثيرا خاصة اتجاهالمقربين ، تجده محبوبمن طرف الكثيرين وذلك لشخصيته البسيطة والخالية من التعقيدات، لذلك تجده حاضر في كل المناسبات العائلية. كما أنه محط اعجاب عند الكثيرين , من أجل عفويته خاصة، وهو على أتم استعداد أن يتعرف بأناس جدد، أو أن يبني علاقات مختلفة، كما أنه يحب تفادي المشاكل والمعضلات، و أيضا يسعده التحدث عن الأفلام ومشاهدتها مع الأصدقاء . صاحب المسار رقم 4 عامل بليد، لكنه اذا عمل عملا فانه يعمله بإتقان شديد وبشغف، ويفضل كل ما هو يدوي وبدائي ، قدراته المهنية عادية، لكنه يحافظ على العمل الجماعي واسسه ومبادئه . ويفضل العمل اليدوي على العمل الالكتروني في الحياة المهنية . يفكر بمستقبله المهني على أنه واعد.  لأنه يرى أن عمل الانسان مرآة لشخصيته . صاحبالمسار رقم 4 يحب الرياضات كثيرا لأنه على دراية بأهميتها وفوائدها الجمة، و يأخذ كل الوقت اللازم من أجله، كما أنه محافظ على نظافة جسده وهندامه .لأنه يريد الحصول على الصحة الجيدة، والحصول على الجسد المناسب و الملائم له ،",
			"url"=>"numberlogia.ar.zmobs.com",
			"en"=>"If a person has the path of life figure 4, he is practical and modest to the junk, his ideas are strong especially for justice and about right and wrong. Organized, systematic and controlled by things in a state of chaos, critical and unflattering, follows a logical and step-by-step approach to problem solving. When he sets his goal and does not budge and seeks to implement it no matter what happens. Since this path is the fourth, he is accompanied by a spontaneous personality, not hesitant but a bit depressing, always anxious and fearful especially in front of the other sex, but he is a very strange person. His morality is good, but his pride is high, he does not like humiliation, he does not like decadence at all, he does not care about complications, and he is quick to respond with the other side. His hopes are also very high. However, he has some problems that he does not want to face in front of the family. He is also very fond of concealing fears and pretending courage in front of others. What distinguishes a person in track No. 4 is that he is happy in his relationships and is easily pleased by the simplest feelings. That is, the success of his relationship is because of his spontaneity and simplicity. His ideas are innocent, but it is rare for his partner to be saved. . . So you find him in his relations a lot, especially the direction of that which insists a lot, or ask a lot of things. The owner of Track No. 4 is very friendly and kind, especially the direction of those close to him. He is loved by many people because of his simple personality, free from complications, so you find him present in all family occasions. He is also admired by many, especially for his spontaneity. He is willing to meet new people or build different relationships. He also likes to avoid problems and dilemmas. He is also happy to talk about films and watch them with friends. The owner of Track No. 4 is a Blade worker, but if he does a job he works with great skill and passion, preferring everything that is manual and primitive, his professional abilities are normal, but he maintains the teamwork, principles and principles. The manual work on electronic work is preferred in professional life. He thinks of his career as promising. Because he sees that man's work is a mirror of his personality. The owner of track # 4 loves sports a lot because he is aware of the importance and benefits of the great, and takes all the time necessary for him, as he maintains the cleanliness of his body and Hndamh. Because he wants to get good health, and get the body appropriate and appropriate,",
			);
			
			$this->numerology_data[4] = array(
			"number"   =>5, 
			"significance" =>"ذا كان لدى الشخص مسار الحياة الرقم 5 ، فهو عاشق للحرية وهي مفتاح شخصيته. يحب السفر والمغامرة والتنوع ومقابلة أشخاص جدد. يتمتلك فضول القط، ويرتكز على التجربة الطويلة في الحياة. يحبذ الانشغال في عدة اشياء في نفس الوقت ويستلذ في ذلك ويكره الثبات وعدمالتنقليريد  التغيير، أشياء جديدة وآفاق جديدة. يمكنه  تكوين صداقات بسهولة، وشخصيته متفائلة وغالبا ملهمة، ويجذب الناس من كافة مناحي الحياة. بما أن هذا المسار هو الخامس فصاحبه شخصية عظيمة وفريدة من نوعها، سعيد جدا و متفاءل، عنيد قليلا، دائم الكلام والثرثرة أمام الآخرين، لكنه إنسان مثقف كثيرا. أخلاقه وصفاته حميدة ، لكن إحساسه قوي ، لا يحب المماطلة والتأخر , لا يكترث بالآخرين , وسريع الغضب والصراخ وأيضا ناشط جدا ، مع هذا فان له شأن لا يقل أهمية و شهرة واسعة كما انه محب كثيرا لإظهار الشخصية والصفات أمام الآخرين.  يحب كلام الآخرين المعسول و يسعد بذلك كثيرا. ما يميز الشخص في المسار رقم 5 أنه يفتخر بشريكه ، لا يهينه بسهولة ، أي أن  فشل علاقاته ليس من أسبابه الاهانة ، وقلة الاهتمام  ، أي أن أفكاره لا تسودها شوائب مثل الاهانة ، لكن من المستبعد أن يجد الشريك المناسب بسهولة . لذلك تجده دائم البحث عن الشخص المناسب الذي قد يراعي مشاعره  ويقتنع به أخيرا ، والذي قد يبادله نفس الاحترام.  صاحب المسار رقم 5 اجتماعي لكن ليس كثيرا، تجده محبوب من البعض وذلك لشخصيته المرحة، عنده بعض الناس المقربين الذي لا يريد أن يتركهم مهما كلف الأمر. كما أنه محط إعجاب عند البعض الذين يقدرونه كثيرا ، وهو على أتم استعداد أن يكسب أصدقاء جدد، أو أن يدافع عن صديق معين ، كما أنه يحب البروز مع الآخرين وإجراء المحادثات لكن الغير مملة أي المهمة، وأيضا يسعده كثيرا التحدث عن الحياة الشخصيةامام المصادر الموثوقة. صاحب المسار رقم  5 عامل بارز وموهوب ، لا يميل كثيرا إلى الملل والشكوك فهم أعدائه  ، بل يفضل كل من هو صادق وحيوي ، قدراته المهنية عالية، لأنه يحافظ على المعتقدات والأسس العملية المهمة من العمل ويطبقها دائما . ويفضل العمل على التسلية في الحياة المهنية  . يفكر بمستقبله المهني على أنه كبير ومهم. لأنه يرى أن العمل أداة لكسب المال وإبراز الذات والاختلاف على الآخرين والمثول بالصورة المناسبة والملائمة. صاحب المسار رقم 5 غير محافظ على صحته باستمرار ، وأخذ الأدوية في وقتها المعين وذلك لأنه يريد الحصول المتعة فقط وليس الأجزاء المملة والحصول على النتائج  بسرعة ، يكره الإصابة، يحاول جاهدا تفادي الطبيب . ",
			"url"=>"numberlogia.ar.zmobs.com",
			"en"=>"If a person has the No. 5 life path, he is a lover of freedom and the key to his personality. He loves traveling, adventure, diversity and meeting new people. It has cat's curiosity and is based on a long life experience. It is desirable to be preoccupied with several things at the same time and to take advantage of it and dislikes the stability and lack of mobility of change, new things and new horizons. He can make friends easily, and his character is optimistic and often inspirational, and attracts people from all walks of life. Since this is the fifth track, he is accompanied by a great and unique personality, very happy and optimistic, a little stubborn, always talking and chattering in front of others, but he is a very educated person. His character traits are benign, but his sense is strong, he does not like procrastination, he does not care about others, he is very quick and angry, and he is very active. He loves the words of others and is very happy. What distinguishes the person in track No. 5 is that he is proud of his partner, not easily insulted, that the failure of his relations is not a cause of insult and lack of attention, that is, his ideas are not dominated by impurities such as insult, but it is unlikely to find the right partner easily. So you find him constantly searching for the right person who may take into account his feelings and finally convinced him, who may exchange the same respect. The owner of Track No. 5 is social but not so much, you find him loved by some and because of his funny personality, he has some close people who does not want to leave them whatever the cost. He is also admired by some who appreciate him a lot. He is willing to win new friends, or to defend a friend. He likes to stand out with others and make conversation but not boring, and he is also very happy to talk about personal life. His track No. 5 is a prominent and gifted worker, not much inclined to boredom and skepticism to understand his enemies; he prefers everyone who is honest and energetic, his professional abilities high, because he maintains the important beliefs and practical foundations of work and always applies them. Preferably work on entertainment in professional life. He thinks of his career as big and important. Because he believes that work is a tool to make money and to highlight the self and differences on others and to appear in a suitable and appropriate. The owner of Track # 5 is constantly conservative and takes medication at his appointed time because he wants to have fun just not boring parts and get results quickly, he hates injury, tries hard to avoid a doctor.",
			);
			
			$this->numerology_data[5] = array(
			"number"   =>6, 
			"significance" =>"إذا كان لدى الشخص مسار الحياة الرقم 6 ، فهو يمتلك حس التعاطف وعاطفة كبيرة تجاه الاخرين ويسعى ليكون في خدمة الآخرين. يقلقه قلة حيلة الضعفاء والمستضعفين والمضطهدين ويسعى لمساندتهم بكل قوة وكانه المعالج والمساعد والمنقذ ولكن عن حسن نية . حب مساعدة الغير اكثر صفة تميزه. بما إن هذا المسار هو السادس فصاحبه شخصية ظريفة وطريفة، مضحكة ومرحة، مزعجة قليلا، دائمة السخرية والسفاهة إمام الآخرين، لكنه إنسان ذكي كثيرا. اخلاقه ليست سيئة ، لكن نفسه منافقة اذ أنه يقول ما لا يفعل ، لا يحب الحزن والكئابة , لا يكترث بالأخرين , وسريع الغضب  وايضا بشوش جدا  ، مع هذا فان له بعض العادات السيئة التي لا تغتفر ،كما انه محب كثيرا لإظهار الفكاهة في الوقت الغير مناسب وأمام الناس الغير مناسبين  . يحب اضحاك الأخرين و يسعد بذلك كثيرا . ما يميز الشخص في المسار رقم  6 أنه مكترث بعلاقاته كثيرا  ، لا يرضخ بسهولة ، أي أن عدم مبالاته تكون سبب في فشل علاقاته  ، وقلة الاهتمام  ، رومنسيته ضئيلة، لكن من المستبعد أن لا يجد الشريك المناسب بسهولة والمكوث معه فترة أكثر . وذلك لروحه المرحة , وبشاشته الكبيرة ونفسه الفريدة والضحكة وأيضا سخافته.  صاحب المسار رقم 6 له إمكانيات اجتماعية كبيرة وغير محدودة ، تجده محبوب من الكثيرين وفقط ذلك لشخصيته الطريفة والمنفردة ، عنده كثير منالناس المقربين الذي لا يريد أن يتركهم. كما أنه يريد بناء علاقات طويلة المدى وجادة  مع البعض الذين يقدرونه كثيرا من أجل ذكاءه ، وهو على أتم استعداد أن يكسب مودة ناس جدد ، كما أنه لا يحب الاقتراب من الناس اليائسين من الحياة والغير متساهلين، وأيضا لا يسعده كثيرا التحدث عن الحياة الشخصية والمشاكل اليومية. صاحب المسار رقم 6 عامل حيوي وذكي، ولكن لا يميل كثيرا الى استخدام ذكاءه في الحياة المهنية، بل يفضل استخدام يديه فقط ، قدراته المهنية جيدة، لأنه يعمل بكل تفاني بيديه ، . ويفضل العمل الجاد في الحياة  المهنية  .  يفكر بمستقبله المهني على أنه محدود. لأنه يرى أن العمل مرتبط باليوم أو غدا لا غير . صاحب المسار رقم 6 محافظ على أكله باستمرار، و أخذ الأدوية في وقتها المعين وذلك لأنه يخاف الطبيب والحقن والمستشفيات بشكل عام.  ولكن اذا استلزم الأمر فانه يعمل المستحيل من أجل استعادة صحته .",
			"url"=>"numberlogia.ar.zmobs.com",
			"en"=>"If the person has the path of life number 6, he has a sense of empathy and passion for others and seeks to be in the service of others. He is concerned about the helplessness of the weak, the oppressed, and the oppressed, and seeks to support them with all strength, and he is the healer, the helper and the savior, but in good faith. Love of others is more characteristic. Since this is the sixth track, he is accompanied by a cute and funny character, funny and fun, a little annoying, always cynical and naive to others, but he is a very intelligent person. His ethics are not bad, but he himself is hypocritical because he says what he does not, does not love sadness and depression, he does not care about others, he is very angry and also very confused. However, he has some unforgivable bad habits and he is very fond of showing humor at the wrong time. And to inappropriate people. He likes to laugh at others and is so happy. What distinguishes a person in Track 6 is that he is very interested in his relationships, does not succumb easily, that is, his indifference is a reason for the failure of his relationships, lack of interest, his romanticity is slim, but he is unlikely to find the right partner easily and stay with him longer. Because of his cheerful spirit, his great pride, his unique self, his laugh and his absurdity. The owner of Track No. 6 has great and unlimited social possibilities, which he finds beloved by many and only for his character, fun and individual, he has many close people who does not want to leave them. He also wants to build long-term and serious relationships with some who appreciate him so much for his intelligence. He is willing to gain the affection of new people. He does not like to get close to people who are desperate for life and others who are too lenient. . His track number 6 is vital and intelligent, but he is not much inclined to use his intelligence in professional life; he prefers to use his hands only, his professional abilities are good, because he works with all his dedication. Preferably work hard in professional life. He thinks of his career as limited. Because he believes that work is linked to the day or tomorrow only. The owner of track No. 6 kept him eating constantly, and taking drugs at the appointed time because he fears the doctor, injections and hospitals in general. But if necessary, he works the impossible to restore his health.",
			);
			
			$this->numerology_data[6] = array(
			"number"   =>7, 
			"significance" =>"إذا كان لدى الشخص مسار الحياة الرقم 7 ، فهو الباحث يبحث عن الحقيقة. لديه إحساس واضح ومقنع لنفسه ككائن روحي. ونتيجة لذلك، يخصص امكانياته في استكشاف المجهول وإيجاد إجابات لأسرار الحياة. يمتلك عقلا غراميا، مفكر تحليلي قادر على التركيز الكبير ولديه بصيرة نظرية. يستمتع بالبحوث وحل الالغاز وال أحاجي الفكرية . بما أن هذا المسار هو السابع فصاحبه شخصية صعبة المراس وتحب البروتوكولات، ذكية جدا ونشيطة، كئيبة قليلا، دائم الترحال والتنقل ولكن في الشروط المعينة، لكنه إنسان ذو قدرات مميزه. اخلاقه يفتخر بها  ، لكن نفسه قوية ، لا يحب الغضب والحرب , لا يهين الأخرين , وسريع الرد  ، مع هذا فان له بعض الخصال الغريبة والسيئة اتجاه بعض المواقف والناس لا اراديا . كما انه محب كثيرا لإظهار الحقيقة أمام الآخرين. ما يميز الشخص في المسار رقم 7 أنه رومانسي في علاقاته  ، لكن طباعه الحادة تكون سبب المشاكل في كثير من الأحيان ، أي أن أفكاره كثير ما تكون خاطئة، لكن أن لا يجد الشريك المناسب المكوث معه الا اذا قلل من طباعه الحادة .  لذلك تجده يجد في البحث  ,  باحثا عن الذييبادله نفس الحب.  صاحب المسار رقم 7 اجتماعي كثيرا، تجده غير محبوب من طرف الكثيرين و فقط ذلك لشخصيته المتسلطة ، مع بعضالناس المقربين. كما أنه محط كره وبغض  عند الكثيرين  الذين يكرهونه كثيرا من أجل مبالغته، وهو على أتم استعداد على أن يتخلى عن شخص ما بمجرد أنه غير منظم أو غير لبق في الكلام والتصرفات المختلفة، أو أن يتخلى عن صديق عزيز وقديم ، كما أنه يحب البروز مع الأثرياء وذوي الصفات الملكية واجراء المحادثاتالمهمة والعالية الهمة ، وأيضا يسعده كثيرا التحدث عن الحياة المترفة.  صاحب المسار رقم 7 عامل مكد، لكنه يبالغ في زيادة الأشياء عن حدها والمبالغة في التجميل الخارجي، بل يفضل كل ما هو مثالي مهما كانت الأسباب  ، قدراته المهنية عالية جدا، لأنه يحافظ على المعتقدات لأنه يحافظ على كل ما هو عملي .ويفضل العمل الجاد فقط في الحياة  المهنية  .  يفكر بمستقبله المهني على أنه مثمر. لأنه يرى أن العمل أداة مهمة لإبراز الذات والاختلاف على الأخرين والمثول بالصورة المناسبة والملائمة.  صاحب المسار رقم 7 يأخذ أدوية الصداع والآلام، وأخذ الأدوية في وقتها المعين. صداعه ناتج عن المبالغة في الردود والثرثرة الزائدة .",
			"url"=>"numberlogia.ar.zmobs.com",
			"en"=>"If a person has a 7-digit life path, he or she is looking for the truth. He has a clear and convincing sense of himself as a spiritual being. As a result, his potential is devoted to exploring the unknown and finding answers to the mysteries of life. He has a grammatical mind, an analytical thinker with great concentration and a theoretical insight. Enjoy research and solve puzzles and intellectual puzzles. Since this is the seventh track, he is accompanied by a tough, anchoring character who loves protocols, very smart and energetic, a little bleak, always traveling and moving, but in certain conditions, but a person with remarkable abilities. His morality is proud of her, but he is strong, does not like anger and war, does not insult others, and is quick to respond, yet he has some peculiarities and bad attitudes towards some people and non-reactionary. . . He is also very fond of showing the truth to others. What distinguishes a person in Track 7 is that he is romantic in his relationships, but his sharp print often causes problems. His ideas are often wrong, but he can not find the right partner to stay with unless he reduces his sharp print. . . So find him find in the search, looking for the same love. The owner of Track No. 7 is very sociable, finds him unloved by many and only for his authoritarian personality, with some close people. . . And he is willing to give up someone as soon as he is unorganized or not to talk and behave differently, or to give up a dear and old friend, and he likes to show off with the rich Who have royal qualities and hold important and high-level talks, and is also very happy to talk about luxury life. His track No. 7 is a stingy factor, but he overstates things by himself and exaggerates in the outer beauty; he prefers everything that is perfect whatever the reasons, his professional abilities are very high, because he maintains beliefs because he keeps everything that is practical. . . Only hard work is preferred in professional life. . . He thinks of his career as fruitful. . . . Because he believes that work is an important tool to highlight the self and the difference to others and to appear in a suitable and appropriate. The owner of track No. 7 takes drugs headache and pain, and taking drugs at the appointed time. . Its rudeness is caused by overstatement and excessive chatter.",
			);
			
			$this->numerology_data[7] = array(
			"number"   =>8, 
			"significance" =>"إذا كان لدى الشخص مسار الحياة الرقم 8 ، فهو موهوب وقائد طبيعي وقادر على تحصيل ثروة كبيرة. لديه موهبة كبيرة للإدارة في جميع مجالات الحياة، وخاصة في مجال الأعمال التجارية والشؤون المالية. لديه فهم عالي في العالم المادي؛ يعمل وفق حدسيه المميز ما يجعله بارعاً يصل الى النجاحات في أي عمل في مختلف المشاريع تقريبا. موهبته لا تكمن في مسك الدفاتر أو الإدارة التافهة، ولكنها من الرؤية والتخطيط وتحديد الاهداف بعيدة المدى. بما أن هذا المسار هو الثامن فصاحبه شخصية طيبة وحنونة، مكترثة جدا وصادقة، مزعج قليلا، دائم الأسئلة والشكوى أمام الآخرين، لكنه إنسان طيب كثيرا. أخلاقه رائعة، لكن نفسه قوية، لا يحب الغضب والحرب, لا يكترث بالآخرين, وسريع الاستجابة وأيضا حنون جدا، مع هذا فان له بعض المخاوف اتجاه بعض الناس كما انه محب كثيرا لإظهار الحب و الحنان الصفات العاطفية أمام الآخرين. ما يميز الشخص في المسار رقم 8 أنه رومانسي في علاقاته  ، يلين و بحب بسهولة ، أي أن  فشل علاقاته يكون سبب في تحطيمه ، أي أن أفكاره لا تسودها خيانة، لكن من النادر أن لا يجد الشريك المناسب بسهولة و المكوث معه  و ذلك لقلة متطلباته.  لذلك تجده يحب بصدق وشغف, مستبعد ذلك الذي قد يهين كرامته ومشاعره، والذي قد لا يبادله نفس الحب.  صاحب المسار رقم 8 اجتماعي كثيرا، تجده محبوب من طرف الكثيرين وفقط ذلك لشخصيته المتساهلة، مع بعض الناس المقربين الذي لا يريد أن يتركهم. كما أنه محط إعجاب  عند الكثيرين الذين يحبونه  كثيرا من أجل روحه، وهو على أتم استعداد أن يكسب حب ناس جدد، أو أن يتخلى عن صديق ماكر ، كما أنه يحب البروز مع الآخرين وإجراء المحادثات غير المهمة، وأيضا يسعده كثيرا التحدث عن الحياة الشخصية امام الأجانب. صاحب المسار رقم 8 عامل مرح، لكنه كسول يميل كثيرا إلى الملل والخمول، بل يفضل كل ما هو راحة واستجمام، قدراته المهنية متوسطة، لأنهلا يحافظ على المعتقدات والأسس العملية المهمة من العمل ويطبقها دائما.  ويفضل الراحة عن  العمل  في الحياة  المهنية  . يفكر بمستقبله المهني على أنه بعيد وصعب وغير مثمر. لأنه يرى أن العمل أداة لكسب المال فقط ولا غير . صاحب المسار رقم 8 يخاف على صحته كثيرا، ويأخذ الأدوية في وقتها المعين وذلك بشراهة كبيرة. لأنه يريد الحصول على الصحة والرشاقة معا، والحصول على النتائج الجيدة، يكره المرض والإصابة، يحاول جاهدا تفادي المستشفى. ",
			"url"=>"numberlogia.ar.zmobs.com",
			"en"=>"If a person has the path of life number 8, he is a talented and natural leader and able to make a fortune. He has a great talent for management in all areas of life, especially in business and finance. He has a high understanding of the physical world; he works in a unique intuitive manner, making him a master of success in any work in almost every project. His talent lies not in bookkeeping or frivolous management, but from vision, planning and long-term goals. Since this is the eighth track, he is accompanied by a good personality, a very attentive and honest person, a little annoying, constantly questioning and complaining in front of others, but a very good person. He is very strong, does not like anger and war, cares about others, is quick to respond and also very affectionate. However, he has some fears towards some people and he is very fond of showing affection and affection for others. What distinguishes a person in Track 8 is that he is romantic in his relationships, easy and easy to love, that is, that the failure of his relationship is a reason to destroy him, that is, his ideas are not dominated by betrayal, but it is rare to find the right partner easily and stay with him because of the lack of requirements. So you find him loves with sincerity and passion, excluded that may insult his dignity and feelings, which may not reciprocate the same love. The owner of track number 8 is very sociable, finding him loved by many and only for his lax personality, with some close people who does not want to leave them. He is also impressed by the many who love him so much for his soul. He is willing to win the love of new people, to abandon a friend who is sly, to love to be with others and to make non-important conversations. He is also very happy to talk about personal life to foreigners . The owner of track number 8 is a cheerful worker, but he is lazy and tends to be bored and idle; he prefers all that is rest and recreation, his professional abilities are mediocre, because he does not maintain the beliefs and practical foundations of work and always applies them. It is preferable to rest from working in a professional life. He thinks of his career as remote, difficult and unproductive. Because he believes that work is a tool to make money only and not. The owner of track number 8 is very much afraid of his health, and takes drugs at the appointed time and with great greed. Because he wants to get health and fitness together, get good results, hate disease and injury, try hard to avoid the hospital.",
			);
			
			
			$this->numerology_data[8] = array(
			"number"   =>9, 
			"significance" =>"إذا كان لدى الشخص مسار الحياة الرقم 9 ، فهو متميز بطيبة القلب وروحه الخيرية والإنسانية، واعي اجتماعيا، وبقلق إزاء حالة العالم. لديه تعاطف كبير ومثالية تجاه الاخرين. افكاره الخيالية جزء مهم منه وسوف يستغل حياته في محاولة لتحقيق بعض جوانب الحلم الخيالي الخاص به، وحتى ان ادى ذلك الى التضحية بالمال والوقت، يؤمن باستخدام الطاقة من أجل عالم أفضل وان العطاء  يؤدي نهاية الامر الى القناعة. بما أن هذا المسار هو التاسع فصاحبه شخصية مبدعة قوية وذو بصيرة ثاقبة، غير مكترثة جدا وجامحة قليلا، مبدع قوي وذو بصيرة ثاقبة، رقيق ومرهف الحس، لا يحاول أن يضايق أحداً أو يجرحه.منفتح  حدسي  شاعري  حكم، سمعته طيبة مع الجميع لا يتقاتل مع أحد  طاهر القلب يحب الطيبين الأخرين و يسعد بهم كثيرا. أهم شيء في حياته هو علاقته بالآخرين . يهتم جداً بهم وبكلامهم ويمتلك قدرات خاصة في فهم الناس جيداً. رقيق ومرهف الحس، لا يحاول أن يضايق أحداً أو يجرحه. سريع الاستجابة للثناء والمديح، وأيضاً النقد ويأخذ النقد بصورة شخصية.  ولهذا فكثيرا ما يتسبب هذا في نفور الناس منه. محاضر ممتاز خصوصاً فيما يتعلق بالاستشارات النفسية والعلاقات اليومية, قائد ملهم ولكنه في نفس الوقت تابع مخلص أيضاً.لديه مشاعر فطرية فياضة ومتأججة.   صاحب المسار رقم 9 اجتماعي، تجده محبوب لكن ليس من طرف الكثيرين وذلك لشخصيته المغرورة المتكبرة، مع بعض الناس المقربين الذي لا يكترث بأحوالهم.  كما أنه محط اعجاب  عند الكثيرين  الذين يحبونه  لترفه وكرمه , وليس من أجل روحه، وهو على أتم استعداد أن يكسب حب ناس بالنقود. ، أو أن يتخلى عن صديق بمقابل مادي ، كما أنه يحب البروز مع الاخرين و ابراز جماله ، وأيضا يسعده كثيرا التحدث عن الحياة المادية امام الأجانب , .يستطيع بسهولة قراءة الآخرين ويؤثر فيهم بالتالي بسهولة أيضاً.  صاحب المسار رقم 9 عامل كسول، لكنه كسول يميل كثيرا الى اعطاء الأوامر والسيطرة، بل يفضل كل ما هو راحة  ، قدراته المهنية محدودة، لأنهلا يحافظ على المعتقداتمن العمل ويطبقها بل يلجأ للأخرين . ويفضل الراحة عن  العمل في الحياة  المهنية  .  يفكر بمستقبله المهني على أنه مثمر.  لأنه يرى أن العمل أداة لكسب المال وانفاقه بسعادة .  يساعد الآخرين في الوصول إلى ذواتهم . فهو يذكر لهم حقائق عن أنفسهم قد لا يعرفونها، ويعلم كيف يطوروا من أنفسهم.  صاحب المسار رقم 9 يخاف على فقدان صحته كثيرا، ويأخذ الأدوية في وقتها المعين لكنه يكثر من المشروبات المضرة. لأنه يريد الحصول علىالصحة بدون تضحيات ، والحصول على النتائج  الجيدة ، يخاف الأمراض والأوبئة المختلفة .",
			"url"=>"numberlogia.ar.zmobs.com",
			"en"=>"If a person has the path of life number 9, he is distinguished by the goodness of the heart, his spirit of charity and humanity, socially conscious, and concerned about the state of the world. He has great compassion and idealism towards others. His imaginative ideas are an important part of him and he will use his life to try to achieve some aspects of his fantasy dream, and even to sacrifice money and time, believes in the use of energy for a better world and that tender ultimately leads to conviction. Since this is the ninth track, he has a strong creative personality with an insightful vision, very unconcerned and a little impertinent, a strong creator and insightful, thin and sensual, not trying to bother or injure anyone. A pure heart loves other good people and is very pleased with them. The most important thing in his life is his relationship with others. They are very interested in their own words and have special abilities in understanding people well. Thin and frail, not trying to bother or injure anyone. Fast response to praise and praise, and also criticism and takes cash in person. This is why people often dislike it. Excellent lecturer especially in terms of psychological counseling and daily relationships, inspiring leader but at the same time loyal follower also. He has innate and intense instinctive feelings. The owner of Track No. 9 is social, loving, but not by many, because of his arrogant arrogant personality, with some close people who do not care about their situation. He is also admired by many who love him for his luxury and generosity, not for his soul, and he is willing to earn people's love of money. , Or to give up a friend in return for money, as he likes to show off with others and highlight his beauty, and also happy to talk about material life in front of foreigners, can easily read others and affect them easily too. His track No. 9 is a lazy worker, but he is lazy and tends to give orders and control; he prefers everything that is comfortable, his professional abilities are limited, because he does not keep the beliefs of work and applies them but resorts to others. It is preferable to rest from working in a professional life. He thinks of his career as fruitful. Because he believes that work is a tool to make money and spend happily. Helps others to reach themselves. He reminds them of facts about themselves they may not know, and knows how to develop from themselves. The owner of track number 9 is afraid of losing his health a lot, and taking drugs at the appointed time, but a lot of harmful drinks. Because he wants to get health without sacrifice, and get good results, afraid of various diseases and epidemics.",
			);
			
			
			$this->numerology_data[9] = array(
			"number"   =>11, 
			"significance" =>"إذا كان لدى الشخص مسار الحياة الرقم 11 ، فهو قادر على أن يكون مصدر إلهام للناس ويملك قدرا هائلا من الطاقة والحدس. هناك الكثير من الاحاسيس الهائجة داخله التي تجعل من حوله يسيء فهمه مما يدفعه الى الخجل والتراجع بالرغم ان لديه امكانيات اكثر مما يعرف. هو يلهم الناس بطاقته من دون جهد مقصود اذ انه يبدو أن الطاقة تتدفق من خلاله  من دون قدرته على التحكم بها.  بما ان هذا المسار هو الحادي عشر فصاحبه شخصية مخادعة و ماكرة، ماهرة جدا ونشيطة، مترددة قليلا، دائمة الكذب والتلاعب، لكنه إنسان كريم ومتساهل في كثير من الأمور . أخلاقه لا يقتدي بها، لكن نفسه جذابة، لا يحب التكبر والغرور, لا يهين الأخرين, وسريع الاستجابة، مع هذا فان له بعض الأفكار المنافقة والسيئة اتجاه بعض المواقف  . كما انه محب كثيرا لإظهار ما هو ليس عليه أمام الآخرين. ما يميز  الشخص في المسار رقم احدى عشر  أنه سرعان ما يشعر بالملل في علاقاته، و طباعه الكريهة تكون سبب المشاكل في كثير من الأحيان ، أي أن أفكاره كثير ما تسودها شوائب ، لكنه إذا وجد الشريك المناسب فانه يريد المكوث قلل من طباعه السيئة .  لذلك تجده مخلصا, باحثا عن الذي يبادله نفس الحب.   صاحب المسار رقم احدى عشر  مخيف قليلا اذ لا تجد العلاقات تنهال عليه ، تجده ماهر في الاختيار كما أنه يختار بعناية أصدقاءه والأشخاص المحيطين به . غير محبوب من طرف الكثيرين، مع إن بعض الناس المقربين يجدون فيه صفات رائعة. كما أنه محط كره وبغض  عند الكثيرين  الذين يمقتونه  كثيرا من أجل حيلته، وهو على أتم استعداد من أجل فعل أي شيء مقابل اقناع الآخرين بما يريدهم أن يقتنعو به .  لذلك فان التعامل مع صاحب هذا المسار ليس بالشيء الهين . صاحب المسار رقم  احدى عشر مسرف قليلا ، لكن له القدرة و الموهبة على اقناع الناس على تشجيعه ،   لكنه يبالغ في تضليل الناس عن الحقيقة ، بل يفضل كل ما هو أحسن وأجمل مهما كان مضللا، قدراته المهنية عالية  ،لأنه يحافظ على كل ما هو عملي . ويفضل  العمل السهل والمثمر في الحياة المهنية  . يفكر بمستقبله المهني على أنه مثمر. صاحب المسار رقم احدى عشر يفضل الموت على العيش بعاهة طول حياته ، إذا شعر بألم فانه يسارع في الذهاب الى طبيب . ويحاول التخلص منه أسرع ما يكون، خوفا من فقدانه صحته .",
			"url"=>"numberlogia.ar.zmobs.com",
			"en"=>"If a person has the path of life number 11, he can be a source of inspiration for people and has a tremendous amount of energy and intuition. There are a lot of raging feelings within him that make him misunderstood, which leads him to shyness and retreat, although he has more possibilities than he knows. He inspires people with his card without intentional effort as energy seems to flow through him without being able to control it. Since this is the eleventh track, he is accompanied by a deceitful and cunnincharacter, very skillful and active, a little hesitant, always lying and manipulating, but he is a generous and tolerant man in many things. His morality is not followed by him, but he is attractive, does not like arrogance and vanity, does not insult others, and is quick to respond. However, he has some hypocritical and bad ideas towards certain positions. He is also very fond of showing what he does not have in front of others. What distinguishes a person in track number eleven is that he soon gets bored in his relationships, and his foul print is often the cause of the problems, that is, his ideas are so pervasive. But if he finds the right partner, he wants to stay down. So you find him sincere, searching for who reciprocates the same love. The owner of track number eleven is a little scary, because he can not find the relationship to him, you find him skilled in the choice and he carefully chooses his friends and people around him. Is not loved by many, although some close people find it wonderful qualities. He is also hated and hated by many who hate him so much for his own good and is ready to do anything in return for convincing others of what he wants them to be convinced of. So dealing with the owner of this track is not easy. The owner of track number eleven is a little extravagant, but he has the ability and talent to convince people to encourage him, but he exaggerates in misleading people about the truth, but prefers everything that is better and more beautiful, no matter how misleading, his professional abilities are high, because he keeps everything that is practical. Preferably easy and productive work in professional life. He thinks of his career as fruitful. The owner of track number eleven prefers death to live a disability throughout his life, if he feels pain, he is quick to go to a doctor. And tries to get rid of him as quickly as possible, for fear of losing his health.",
			);
			
			
			$this->numerology_data[10] = array(
			"number"   =>22, 
			"significance" =>"إذا كان لدى الشخص مسار الحياة الرقم 22 ، فهو من أنجح الشخصيات مقارنة من كل أرقام مسار الحياة اذ تتوفر له اقصى احتمالات الحياة: فمن ناحية، لديه القدرة على أن يكون شخص بناء، وقادر على إدراك اشياء عظيمة في العالم. من ناحية أخرى، يمكنه الانزلاق إلى أعماق الغموض، وتحقيق ذاته وايجاد مفاتيح شخصيته. يستخدم الفضيلة المثل العليا والرؤية استخدامها لإلهام الآخرين للانضمام اليه في غايته.  بما ان هذا المسار هو اثنين و عشرين فصاحبه شخصية حماسية ، محبة للحياة ، متفائلة وشغوفة ، نشيطة ، جريئة قليلا ، دائمة القناعة ، حساس ودرامي زيادة عن اللزوم , لكنه انسان ملتزم وذا عقائد سليمة مبنية على اسس صادقة . في كثير من الأمور . اخلاقه عالية لكنه , يهوى تكبير الأشياء الصغيرة ، لكن نفسه جذابة ، لا يهين الآخرين ، مع هذا فان له بعض الأفكار السخيفة . كما انه محب كثيرا لمساعدة الآخرين. ما يميز الشخص في المسار رقم اثنين وعشرين أنه يحب اظهار محاسنه للحبيب ويبالغ بذلك كثيرا . ، يحاول جاهدا إخفاء نقاط ضعفه لكنه لطالما يفشل في ذلك . محب للكمال اذ أنه مخطأ في اعتقاده ، أن العلاقات العاطفية يجب أن تكون مثالية لا تشوبها شوائب . صاحب المسار رقم اثنين وعشرين، تجده اجتماعي محب وودود، يحب السهرات، الحفلات والأجواء العائلية خاصة.  يغفر أخطاء الآخرين اذا اعتذروا . ، كما أنه مسامح لكن لا ينسى مساوئ الغير. لكنه لا يحقد بل دائما يحاول تفهم الآخرين والأسباب التي دفعتهم الى القيام بالأمور الخاطئة . كما أنه يحب مساعدة الآخرين لكن ان طلبوا المساعدة . اذ أنه لا يقحم نفسه فيما لا يعنيه .  صاحب المسار رقم اثنين وعشرين يكره الأعمال الشاقة والمتعبة . معتقدا أنها قد تضعفه أو قد تهلك إنتاجه المستقبلي، لكن له القدرة والموهبة على الإبداع والابتكار، لكنه يبالغ في تشويه أصل الشيء بل يحب تغيير كل شيء عن أصله، قدراته المهنية عالية، لأنه عملي.  ويفضل العمل التكنولوجي في الحياة المهنية . يفكر بمستقبله المهني على أنه ذاهب للأحسن. صاحب المسار رقم اثنين وعشرين لا يحافظ كثيرا على نظام حميته الغذائي، كما أنه يفضل أكل وجبة سريعة على ممارسة التمارين الشاقة والمتعبة، مهما علم إنها خطيرة على صحته ورشاقته. لكنه يندم بعد ذلك . ويتمنى لو أنه قلل من عدم مبالاته.",
			"url"=>"numberlogia.ar.zmobs.com",
			"en"=>"If a person has the path of life number 22, he is one of the most successful figures compared to all the life-cycle figures. He has the greatest potential for life: on the one hand, he has the ability to be a constructive person, capable of perceiving great things in the world. On the other hand, he can slide into the depths of mystery, realize himself and find the keys to his personality. Virtue uses ideals and vision to use them to inspire others to join them to their ends. Since this path is twenty-two, his personality is passionate, life-loving, optimistic and eager, energetic, a little bold, persistent, sensitive and over-dramatic, but a committed person with sound beliefs based on honest foundations. In many things. His morality is high but he likes to enlarge the small things, but the same attractive, do not insult others, with this he has some silly ideas. He is also very fond of helping others. What distinguishes a person in track number twenty-two is that he likes to show his favors to the lover and exaggerates so much. , Tries hard to hide his weaknesses but has always failed to do so. A lover of perfection because he is mistaken in his belief that emotional relationships must be impeccable and perfect. His track number twenty-two, you find a sociable loving and friendly, loves weddings, parties and family atmosphere especially. He forgives the mistakes of others if they apologize. , As he forgives but does not forget the disadvantages of others. But he does not hate, but always tries to understand others and the reasons that led them to do the wrong things. He also likes helping others but they ask for help. He does not intrude on what he does not mean. His track number twenty-two hates hard work and tired. Believing that it may weaken him or may destroy his future production, but he has the ability and talent for creativity and innovation, but exaggerates the distortion of the origin of the thing, but loves to change everything about his origin, his professional abilities, because it is practical. Preferably technological work in professional life. He thinks of his professional future as going for the better. The owner of track number twenty-two does not keep much of his diet diet, as he prefers to eat a quick meal to exercise hard and tired, no matter how dangerous it is to his health and grace. But he regrets afterwards. He wished he had underestimated him.",
			);
			
		}
		
		public function getData($number){
			//get the value here and return the result
			foreach($this->numerology_data as $value){
				if($value['number']==$number){
					return $value['significance'];
				}
		    }
	
	    }
    }
?>
