package com.zeta.mobile.direct.offers.admin.generic;

import com.fasterxml.jackson.annotation.JsonFormat;

@JsonFormat(shape = JsonFormat.Shape.OBJECT)
public enum ResponseStatus {
	OK(0, "SUCCESS"), 
	CARRIER_NOT_FOUND(-1, "CARRIER NOT FOUND"), 
	CAMPAIGN_NOT_FOUND(-2,"CAMPAIGN NOT FOUND"), 
	CAMPAIGN_NAME_IS_NULL(-3, "CAMPAIGN NAME CAN NOT BE NULL"), 
	MSISDN_IS_NULL(-4, "MSISDN CAN NOT BE NULL"), 
	CARRIER_IS_NULL(-5, "CARRIER ID (OPERATOR ID) CAN NOT BE NULL"), 
	IMPRESSION_IS_NULL(-6, "IMPRESSION ID CAN NOT BE NULL"), 
	IMPRESSION_NOT_FOUND(-7, "IMPRESSION NOT FOUND"),
	CAMPAIGN_OFFER_NOT_FOUND(-8, "CAMPAIGN OFFER NOT FOUND"),
	UNDEFINED_SALES_CHANNEL(-9, "UNDEFINE SALES CHANNEL: HeaderEnrichmentReferenceCode is null and sendVerificationSMS is setted to false"),
	BROWSER_LANGUAGE_IS_NULL(-10, "BROWSER LANGUAGE CAN NOT BE NULL"), 
	IP_IS_NULL(-11, "IP CAN NOT BE NULL"), 
	INVALID_MSISDN(-12, "INVALID MSISDN"), 
	SUBSCRIPTION_ID_IS_NULL(-13, "SUBSCRIPTION ID IS NULL"), 
	SUBSCRIPTION_NOT_EXISTS(-14, "SUBSCRIPTION NOT EXIST"), 
	SUBSCRIPTION_REQUEST_ALREADY_ANSWER(-15, "SUBSCRIPTION REQUEST ALREADY ANSWER"),
	SUBSCRIPTION_CONTRACT_ID_IS_NULL(-16, "SUBSCRIPTION CONTRACT ID CAN NOT BE NULL"), 
	INVALID_RENEW_DATE(-17, "SUBSCRIPTION RENEW DATE IS INVALID"), 
	SUBSCRIPTION_FAIL_ON_PARTNER(-18, "SUBSCRIPTION REQUEST TO PARTNER FAILED"), 
	USER_ALREADY_SUBSCRIBED(-19, "USER ALREADY SUBSCRIBED TO THIS SERVICE"), 
	PIN_VERIFICATION_FAIL_ON_PARTNER(-20, "USER PIN INSERTED NOT VALID AT PARTNER"),
	SUBSCRIPTION_IS_NOT_PREACTIVE(-21, "ONLY SUBSCTRITPIONS WITH STATUS PREACTIVE CAN BE ACTIVATED BY PIN CODE"), 
	IS_NOT_PIN_CODE_FLOW(-22, "SUBSCTRITPION IS NOT IN A PIN CODE VERIFICATION FLOW");

	private final long code;
	private final String description;

	ResponseStatus(long code, String description) {
		this.code = code;
		this.description = description;
	}

	public long getCode() {
		return this.code;
	}

	public String getDescription() {
		return this.description;
	}
}
